---
# configuration for GitHub Actions
name: simboard tests
on:
    push:
    pull_request:
jobs:
    wrapper-simavr:
        name: Build and test wrapper-simavr
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - name: Dependencies
              run: |
                sudo apt-get -y install \
                    libsimavr-dev
                curl -L -o lws.tgz https://github.com/warmcat/libwebsockets/archive/refs/tags/v4.3.3.tar.gz
                tar -xzf lws.tgz
                cd libwebsockets-4.3.3
                mkdir build && cd build && cmake ..
                make && make install
            - name: Build
              run: |
                cd wrapper-simavr
                mkdir build && cd build && cmake ..
                make
